apiVersion: api.omerrevach.online/v1alpha1
kind: Scaler
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: scaler-sample
spec:
  # TODO(user): Add fields here
