apiVersion: api.omerrevach.online/v1alpha1
kind: Scaler
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: scaler-sample
spec:
  # TODO(user): Add fields here
  start: "23:00"
  end: "23:50" 
  replicas: 3
  normalReplicasAmount: 1
  timezone: "Asia/Jerusalem"
  deployments:
    - name: nginx
      namespace: default
    # - name: app2
    #   namespace: default
    # - name: app3
    #   namespace: default