apiVersion: api.omerrevach.online/v1alpha1
kind: Scaler
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: scaler-sample
spec:
  # TODO(user): Add fields here
  start: "16:30"
  end: "18:00" 
  replicas: 5
  normalReplicasAmount: 2
  timezone: "Asia/Jerusalem"
  deployments:
    - name: app1
      namespace: default
    - name: app2
      namespace: default
    - name: app3
      namespace: default